use master 
go

if exists (select name from sys.databases where name = 'DM_NORTHWIND')
	Begin
		Drop database DM_NORTHWIND
	End
go
CREATE DATABASE DM_NORTHWIND
GO

USE DM_NORTHWIND
GO

CREATE TABLE DIM_CLIENTE (
  CLIENTE_KEY INT IDENTITY(1,1) NOT NULL,
  COD_CLIENTE VARCHAR(7),
  NOMBRE_CLIENTE VARCHAR(52) NOT NULL,
  PRIMARY KEY(CLIENTE_KEY)
);
GO

CREATE TABLE DIM_EMPLEADO (
  EMPLEADO_KEY INT IDENTITY(1,1) NOT NULL,
  COD_EMPLEADO INT NOT NULL,
  NOMBRE_COMPLETO VARCHAR(41) NULL,
  PRIMARY KEY(EMPLEADO_KEY)
);
GO

CREATE TABLE DIM_TIEMPO (
  TIEMPO_KEY INT IDENTITY(1,1) NOT NULL,
  COD_TIEMPO VARCHAR(8),
  ANIO INT NOT NULL,
  MES INT NOT NULL,
  DIA INT NOT NULL,
  NOMBRE_MES VARCHAR(12) NOT NULL,
  PRIMARY KEY(TIEMPO_KEY)
);
GO

CREATE TABLE DIM_ORDEN_COMPRA (
  ORDEN_KEY INT IDENTITY(1,1) NOT NULL,
  COD_ORDEN INTEGER NOT NULL,
  PRIMARY KEY(ORDEN_KEY)
);
GO

CREATE TABLE DIM_PRODUCTO (
  PRODUCTO_KEY INT IDENTITY(1,1) NOT NULL,
  COD_PRODUCTO INTEGER NOT NULL,
  NOMBRE_PRODUCTO VARCHAR(52) NOT NULL,
  PRIMARY KEY(PRODUCTO_KEY)
);
GO

CREATE TABLE DIM_TERRITORIO (
  TERRITORIO_KEY INT IDENTITY(1,1) NOT NULL,
  CODIGO_TERRITORIO VARCHAR(26) NOT NULL,
  NOMBRE_TERRITORIO VARCHAR(65) NOT NULL,
  PRIMARY KEY(TERRITORIO_KEY)
);
GO

CREATE TABLE FACT_NORTHWIND (
  FK_ORDEN INTEGER NOT NULL,
  FK_CLIENTE INTEGER NOT NULL,
  FK_EMPLEADO INTEGER NOT NULL,
  FK_PRODUCTO INTEGER NOT NULL,
  FK_TERRITORIO INTEGER NOT NULL,
  FK_TIEMPO INTEGER NOT NULL,
  CANTIDAD_PRODUCTO INTEGER NOT NULL
 );
GO

ALTER TABLE FACT_NORTHWIND
ADD CONSTRAINT FK__FACT_NORT__FK_CL__4316F928 FOREIGN KEY (FK_CLIENTE) REFERENCES DIM_CLIENTE(CLIENTE_KEY);

ALTER TABLE FACT_NORTHWIND
ADD CONSTRAINT FK__FACT_NORT__FK_EM__440B1D61 FOREIGN KEY (FK_EMPLEADO) REFERENCES DIM_EMPLEADO(EMPLEADO_KEY);

ALTER TABLE FACT_NORTHWIND
ADD CONSTRAINT FK__FACT_NORT__FK_OR__4222D4EF FOREIGN KEY (FK_ORDEN) REFERENCES DIM_ORDEN_COMPRA (ORDEN_KEY);

ALTER TABLE FACT_NORTHWIND
ADD CONSTRAINT FK__FACT_NORT__FK_PR__44FF419A FOREIGN KEY (FK_PRODUCTO) REFERENCES DIM_PRODUCTO(PRODUCTO_KEY);

ALTER TABLE FACT_NORTHWIND
ADD CONSTRAINT FK__FACT_NORT__FK_TE__45F365D3 FOREIGN KEY (FK_TERRITORIO) REFERENCES DIM_TERRITORIO(TERRITORIO_KEY);

ALTER TABLE FACT_NORTHWIND
ADD CONSTRAINT FK__FACT_NORT__FK_TI__46E78A0C FOREIGN KEY (FK_TIEMPO) REFERENCES DIM_TIEMPO(TIEMPO_KEY);
GO


--ALTER AUTHORIZATION ON DATABASE :: DM_NORTHWIND TO SA